version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: postgres
      DB_HOST: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      DATABASE_URL: postgresql://postgres:1234567@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata: